{% set name = "trefide" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ikinsella/trefide/archive/{{ version }}.tar.gz
  sha256: 7efea399870d510354fc1683d0146a9d856ae5178b92b6c5c0688d9c0f87b38a 

build:
  number: 0
  skip: true  # [py2k or not linux]

requirements:
  build:
#    - {{ compiler('c') }}
#    - make
    - python =3.6
    - numpy
    - scipy
    - matplotlib
    - mkl-devel {{ mkl }}
    - cython >=0.27.3
    - cycler

#  build:
#    - {{ compiler('c') }}
#    - make
#    - python
#    - numpy
#    - mkl-devel {{ mkl }}
#    - cython >=0.27.3

  run:
    - python =3.6
    - numpy
    - scipy
    - matplotlib
    - mkl-devel {{ mkl }}
    - jupyterlab =0.35
    - scikit-learn
    - opencv >=4.1.0
    - cycler

test:
  imports:
    - trefide.pmd

about:
  home: https://github.com/ikinsella/trefide/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'TreFiDe is the software package accompanying the research publication Penalized matrix decomposition for denoising, compression, and improved demixing of functional imaging data.'
  description: 'TreFiDe is an imporved appproach to compressing and denoising functional image data. The method is based on a spatially-localized penalized matrix decomposition (PMD) of the data to separate (low-dimensional) signal from (temporally-uncorrelated) noise.'
  doc_url: https://github.com/ikinsella/trefide/tree/master/doc
  dev_url: https://github.com/ikinsella/trefide/

extra:
  recipe-maintainers:
    - JW3132
    - ikinsella
